{% set name = "lintquarto" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lintquarto-{{ version }}.tar.gz
  sha256: 1c3e23510a4cfcc710fe7bd15f828ea1302647ee93f92b73889bc595a9d8ee07

build:
  entry_points:
    - lintquarto = lintquarto.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit
    - pip
  run:
    - python >={{ python_min }}
    - toml

test:
  imports:
    - lintquarto
  commands:
    - pip check
    - lintquarto --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://lintquarto.github.io/lintquarto/
  summary: Package for running linters, static type checkers and code analysis tools on python code in quarto (.qmd) files.
  dev_url: https://github.com/lintquarto/lintquarto
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amyheather
