{% set version = "0.10.0" %}

package:
  name: lintquarto
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/lintquarto/lintquarto-{{ version }}.tar.gz
  sha256: d004e63f30779047d89182557e0ac738177e851f9b4a9e19f14929e2506f6b7b

build:
  entry_points:
    - lintquarto = lintquarto.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - flit
    - pip
  run:
    - python >=3.9
    - toml
    - pyyaml

test:
  imports:
    - lintquarto
  commands:
    - pip check
    - lintquarto --help
  requires:
    - pip
    - python >=3.9

about:
  home: https://lintquarto.github.io/lintquarto/
  summary: Package for running linters, static type checkers and code analysis tools on python code in quarto (.qmd) files.
  dev_url: https://github.com/lintquarto/lintquarto
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amyheather
